FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8

RUN mkdir -p /deps
RUN ldd /repo/build/tools/acl_compressor/main_generic/acl_compressor | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/build/tools/acl_compressor/main_generic/acl_compressor /repo/build/tools/acl_compressor/main_generic/acl_compressor
ENV LD_LIBRARY_PATH=/deps
